# Documentation: /docs/groups.md


---
- name: Create groups
  hosts: localhost

  tasks:
    - name: Ensure developer group exists
      ansible.builtin.group:
        name: developer
        state: present

    - name: Ensure group "admin" exists
      ansible.builtin.group:
        name: admin
        state: present
