# Documentation: /docs/smoke.md
# one playbook for service

# or one playbook for download all containers
# or one playbook for running all containers
# then playbooks for other stuff


- name: Smoke Tests
  hosts: localhost
  tasks:
    - name: Ping my host
      ansible.builtin.ping:

    - name: Print Hello World
      ansible.builtin.debug:
        msg: Hello World