# Documentation: /docs/users.md

- name: Create a user 'dev1' with a home directory
  ansible.builtin.user:
    name: dev1
    create_home: yes

- name: Add the user 'dev1' with a, appending the group 'developer' to the user's groups
  ansible.builtin.user:
    name: dev1
    groups: developer
    append: yes

- name: Create a 2048-bit SSH key for user dev1 in ~dev1/.ssh/id_rsa
  ansible.builtin.user:
    name: dev1
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa




- name: Create a user 'dev2' with a home directory
  ansible.builtin.user:
    name: dev2
    create_home: yes

- name: Add the user 'dev2' with a, appending the group 'developer' to the user's groups
  ansible.builtin.user:
    name: dev2
    groups: developer
    append: yes

- name: Create a 2048-bit SSH key for user dev2 in ~dev2/.ssh/id_rsa
  ansible.builtin.user:
    name: dev2
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
